# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170713_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
